INSERT INTO users (nickname, mail, password)
values (
        'Zancivinne',
        'boehm.norag@yahoo.com',
        '111TzLO3pgw4F'
    ),
    (
        'Ephilawali',
        'wyman.aniya@yahoo.com',
        '222wEIHDMm1R2'
    ),
    (
        'Quinan',
        'rbodeasdemalia@gmail.com',
        '333g8FVHjBcuh'
    ),
    (
        'Lassylil',
        'marcel.douglas@yahoo.com',
        '444LntrttCMmF'
    );